### ISSUE TITLE
Need to explicitly install webidl-conversions

### ISSUE THREAD

**Issue by ngryman** [lukechilds/browser-env#59]
Hey,

I'm using `browser-env@3.2.1` and I've got a the following error:
<details>

```sh
Error: Cannot find module 'webidl-conversions'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ngryman/Projects/react-element-portal/node_modules/domexception/lib/DOMException.js:3:21)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ngryman/Projects/react-element-portal/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ngryman/Projects/react-element-portal/node_modules/domexception/lib/public-api.js:3:18)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
```

</details>
<br>

Explicitly installing the `webidl-conversions` package resolves the problem. I don't know if it's related to `jsdom` though.

**Comment by lukechilds** [comment]
In a fresh directory I get:

```
$ npm install browser-env
+ browser-env@3.2.1
added 94 packages in 4.853s

$ node -e "console.log(require('browser-env'))"
[Function: browserEnv]
```

Possibly something strange in your setup?

Gonna close this issue as it seems to be unrelated to `browser-env` or `jsdom`. Feel free to re-open if you find otherwise.

**Comment by ngryman** [comment]
@lukechilds Thanks for the feedback. I am using it with `ava` following their guide: https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md.

I'll dig a little deeper my side to see if it could be related to my setup, which is kind of basic, and get back to you.

**Comment by ngryman** [comment]
For posterity, removing my `package-lock.json` file and doing a fresh install worked. It might come from the fact I was using `jsdom` before switching to `browser-env`, and somehow `npm` got lost on the way 🤷‍♂️

**Comment by lukechilds** [comment]
npm 5 is buggy as hell, you should use either npm 4 or yarn.

I can't tell you the amount of development hours I lost on npm 5 due to it doing weird shit.
